spree_product_import/config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  post 'admin/products/import', to: 'admin/products#import'
end

spree_product_import/app/models/spree_product_import/configuration.rb
module SpreeProductImport
  class Configuration < Spree::Preferences::Configuration

   # Some example preferences are shown below, for more information visit:
   # https://guides.spreecommerce.org/developer/core/preferences.html

   # preference :visible, :boolean
   # preference :dark_chocolate, :boolean, default: true
   # preference :color, :string, default: 'Red'
   # preference :favorite_number, :integer
   # preference :supported_locales, :array, default: [:en]
  end
end

spree_product_import/app/controllers/products_controller_decorator.rb
module Spree
  ProductsController.class_eval do
    def import
      puts "Yes, this was hit."
    end
  end
end

spree_product_import/app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Product) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_product), new_object_url, { class: "btn-success", icon: 'add.svg', id: 'admin_new_product' } %>
  <%= render partial: 'spree/admin/products/shared/import' %>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {f: f} %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :search_by_name, Spree.t(:name) %>
            <%= f.text_field :search_by_name, size: 15, class: "form-control js-quick-search-target js-filterable" %>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, size: 15, class: "form-control js-filterable" %>
          </div>
        </div>
        <div class="col-12">
          <div class="field checkbox mb-2">
            <label>
              <%= f.check_box :deleted_at_null, {checked: params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              <%= Spree.t(:show_deleted) %>
            </label>
          </div>

          <div class="field checkbox mb-2">
            <label>
              <%= f.check_box :not_discontinued, {checked: params[:q][:not_discontinued] == '0'}, '0', '1' %>
              <%= Spree.t(:show_discontinued ) %>
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search.svg' %>
      </div>
    <% end %>

  </div>
<% end %>

<% if @collection.any? %>
<div class="table-responsive">
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th scope="col" colspan="2"><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
        <th scope="col"><%= Spree.t(:sku) %></th>
        <th scope="col"><%= Spree.t(:status) %></th>
        <th scope="col" class="text-center">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, {title: 'admin_products_listing_price_title'} %>
        </th>
        <th scope="col" data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
        <% available_status = available_status(product) %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td scope="row" class="image">
              <%= link_to edit_admin_product_path(product) do %>
                <%= mini_image product %>
              <% end %>
            </td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="status"><%= active_badge(available_status == Spree.t(:available), label: available_status) %></td>
            <td class="text-center"><%= display_price(product) %></td>
            <td class="actions " data-hook="admin_products_index_row_actions">
              <span class="d-flex justify-content-end">
                <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
                <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
                <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
              </span>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Product) %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

spree_product_import/app/views/spree/admin/products/shared/_import.html.erb
<script>
function toggleImport() {
  $("#products_import_modal").toggle();
}
</script>

<style type="text/css">
  #products_import_modal {
    position: absolute;
    right: 1em;
    top: 1em;
    height: 12em;
    width: 30em;
    border: 1px solid black;
    border-radius: 4px;
    background-color: white;
    
    z-index: 2;
  }

  #close_product_import_modal {
    background-color: black;
    border-radius: 4px;
    color: white;
    font-weight: bold;
  }

  div.modal_title {
    font-weight: bold;
    font-size: 1.25em;
  }
</style>

<%= button_link_to I18n.t('import'), '#', onclick: 'toggleImport()' %>

<div id="products_import_modal" style="display: none;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-8 text-left modal_title">Import Products File</div>
      <div class="col-4 text-right">
        <%= button_link_to 'X', '#', onclick: 'toggleImport()', id: 'close_product_import_modal' %>
      </div>
    </div>
    <div class="row">
      <div class="ml-2 col-9 text-truncate"><%= file_field_tag I18n.t('file_name') %></div>
      <div class="mr-2 col-2"><%= button_link_to I18n.t('upload'), '#', onclick: 'uploadFile()', id: 'close_product_import_modal' %></div>
    </div>
    <div class="row p-2">
      <div id="products_import_progress" class="p-2 col-12 border border-success rounded">
        <div id="products_import_progress_percent" class="float-left pt-2">0%</div>
        <div class="float-right">
          <%= button_link_to I18n.t('cancel'), '#', onclick: 'uploadFile()', id: 'close_product_import_modal', class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>